name: 部署携程项目到GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 安装Node.js环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装项目依赖
        run: npm install

      - name: 构建项目生成静态文件
        run: |
          echo "HOME_PAGE=https://neithardtpeta-rgb.github.io/Neithardtpetargbxiechen/" > .env.production
          npm run build

      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
